### ISSUE TITLE
[BUG]: A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'

### ISSUE THREAD

**Issue by ignxal** [microsoft/azure-pipelines-extensions#1247]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-extensions/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Extension name

ArcGIS EB Dependency Validator

### Extension version

any

### Issue Description

I'm developing a custom Azure DevOps task using Node.js.
When I install the extension and try to run the task inside a pipeline, I get the following error:

> A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'.

I expected the task to execute normally, as the task.json specifies handlers for Node10, Node16, and Node20_1, and the agent is running on a Windows x64 system.
The task's execution section looks like this:

```
"execution": {
  "Node10": {
    "target": "index.js",
    "argumentFormat": ""
  },
  "Node16": {
    "target": "index.js",
    "argumentFormat": ""
  },
  "Node20_1": {
    "target": "index.js",
    "argumentFormat": ""
  }
}
```
The buildandreleasetask/ folder in the .vsix package contains:

- index.js
- task.json
- package.json

And the .vsix root includes vss-extension.json.

The agent version is compatible (4.254.0), and the pipeline is configured correctly.
However, the error persists and the task is skipped without executing.
I also tried running the Microsoft-hosted **windows-latest** image and went through older issue-related posts.

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [x] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 10 x64

### Relevant log output

```shell
##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
trigger:
  - main
  - develop

pool: mypool or windows-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '20.x'
          - task: arcgis-eb-dependency-validator@1
            inputs:
              pkgJsonPath: '$(Build.Repository.LocalPath)/$(Build.Repository.Name)/package.json'
              builderVersion: 'ArcGISExperienceBuilder_1.15'
              portalVersion: 'ArcGISPortal_11.1'
              azdoPat: '<token>'
```
