### ISSUE TITLE
[Terraform Task] integrate output in pipeline vars

### ISSUE THREAD

**Issue by StefanSchoof** [microsoft/azure-pipelines-extensions#660]
I have some terraform files defining output. Some of this output I need in further steps as variables to configure my system. I think having a way to put a terraform output to a azure pipeline variable would be useful.

**Comment by RoshanKumarMicrosoft** [comment]
This feature is already in task in case of Terraform apply operation
![TerraformExtensionOutputVariable](https://user-images.githubusercontent.com/33001640/62678910-6a580400-b9d0-11e9-9434-98a8a0148356.PNG)

**Comment by StefanSchoof** [comment]
Great, sorry that I missed that.

**Comment by StefanSchoof** [comment]
I use this Powershell to get the json values to devops variables:

```powershell
$jsonPath=(Get-ChildItem env:TERRAFORMTASK*_JSONOUTPUTVARIABLESPATH).Value
Write-Host "Convert terrafrom output from $jsonPath to devops vars."
$json=Get-Content $jsonPath | ConvertFrom-Json
$json `
    | Get-Member -type NoteProperty `
    | ForEach-Object {
        $o=$json."$($_.Name)"
        "##vso[task.setvariable variable=$($_.Name);isOutput=true$(if ($o.sensitive -eq "True") {";issecret=true"})]$($o.value)"
    }
```

**Comment by JleruOHeP** [comment]
Any chance to have an example of how to get those outputs in yaml-defined pipeline?
For example, I have 

```
    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-infrastructure/'
        commandOptions: '-var="terraform_service_principal_client_id=$(client-id)" -var="terraform_service_principal_client_secret=$(client-secret)" -var="subscription_id=$(subscription-id)" -var="environment=dev"'
        environmentServiceNameAzureRM: 'My State Subscription'
```

How to get the output variables in this case?
