### ISSUE TITLE
terraform: make apply consume saved plan

### ISSUE THREAD

**Issue by maximbaz** [microsoft/azure-pipelines-extensions#686]
In our pipeline we execute terraform commands in the following order:

- terraform plan
- terraform apply

In order to make sure that `apply` will do exactly what `plan` has printed, we must save the output of the `plan` and then pass it to the `apply` command.

It seems `plan` (contrary to `onlyPlan`) is actually able to save the result of the `plan` into a file whose path is saved to `jsonPlanFilePath` variable, but it doesn't seem possible to make `apply` consume the plan saved in `jsonPlanFilePath` (?).

Ideally, I'd control it with a new parameter, something like this:

```
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: "Terraform: plan"
  inputs:
    command: plan

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: "Terraform: apply"
  inputs:
    command: onlyApply
    plan: $(jsonPlanFilePath)

```
