### ISSUE TITLE
Got error when executing in multistage deployment job

### ISSUE THREAD

**Issue by rhollins** [microsoft/azure-pipelines-extensions#724]
Hello

The extension works fine when used inside a normal job but fails when executed inside deployment job:

FAILS

```
  - stage: main_pipeline
    displayName: 'main pipeline'
    jobs:

    - deployment: main_pipeline
      displayName: 'Main Pipeline'
      pool:
        vmImage: 'ubuntu-latest'
      environment: ${{ parameters.environment }}
      strategy:
        runOnce:
          deploy:
             steps:

              - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
                displayName: "Terraform: init"
                inputs:
                  command: init
                  backendType: azurerm
                  workingDirectory: ./env/hub/terraform/
                  #commandOptions: 
                  backendServiceArm: ${{ parameters.scHub }}
                  backendAzureRmResourceGroupName: ${{ parameters.stateRgName }}
                  backendAzureRmStorageAccountName: ${{ parameters.stateSaName }}
                  backendAzureRmContainerName: ${{ parameters.stateContainerName }}
                  backendAzureRmKey: ${{ parameters.backendAzureRmKey }}
```

WORKS

```
  - stage: main_pipeline
    displayName: 'main pipeline'
    jobs:

    - job: test_job
      displayName: 'Test Job'
      pool:
        vmImage: 'ubuntu-latest'     
      steps:

              - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
                displayName: "Terraform: init"
                inputs:
                  command: init
                  backendType: azurerm
                  workingDirectory: ./env/hub/terraform/
                  #commandOptions: 
                  backendServiceArm: ${{ parameters.scHub }}
                  backendAzureRmResourceGroupName: ${{ parameters.stateRgName }}
                  backendAzureRmStorageAccountName: ${{ parameters.stateSaName }}
                  backendAzureRmContainerName: ${{ parameters.stateContainerName }}
                  backendAzureRmKey: ${{ parameters.backendAzureRmKey }}
```

ERROR:

##[debug]task result: Failed
##[error]Error: There was an error when attempting to execute the process '/usr/local/bin/terraform'. This may indicate the process failed to start. Error: spawn /usr/local/bin/terraform ENOENT
##[debug]Processed: ##vso[task.issue type=error;]Error: There was an error when attempting to execute the process '/usr/local/bin/terraform'. This may indicate the process failed to start. Error: spawn /usr/local/bin/terraform ENOENT
##[debug]Processed: ##vso[task.complete result=Failed;]Error: There was an error when attempting to execute the process '/usr/local/bin/terraform'. This may indicate the process failed to start. Error: spawn /usr/local/bin/terraform ENOENT
