### ISSUE TITLE
Terraform: irrelevant error message if working directory does not exist

### ISSUE THREAD

**Issue by algattik** [microsoft/azure-pipelines-extensions#780]
Pipeline YAML:

```
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
    displayName: Terraform init
    inputs:
      workingDirectory: a/directory/that/does/not/exist
```

Output:

```
Starting: Terraform init
==============================================================================
Task         : Terraform
Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
Version      : 0.0.142
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
==============================================================================
/opt/hostedtoolcache/terraform/0.12.20/x64/terraform init -backend-config=storage_account_name=dataopsterraform -backend-config=container_name=terraformstate -backend-config=key=test.tfstate -backend-config=resource_group_name=dataops-terraform -backend-config=arm_subscription_id=a4ed7b9a-b128-49b4-a6ee-fd07ff6e296d -backend-config=arm_tenant_id=*** -backend-config=arm_client_id=*** -backend-config=arm_client_secret=***
##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/0.12.20/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/0.12.20/x64/terraform ENOENT
Finishing: Terraform init
```

Expected error message:
```
The directory a/directory/that/does/not/exist does not exist.
```
