### ISSUE TITLE
[Bug] TerraformTaskV1@0 with DownloadSecureFile@1 doesn't work toegether

### ISSUE THREAD

**Issue by rrmistry** [microsoft/azure-pipelines-extensions#787]
Bringing this here from [Azure DevOps user voice](https://developercommunity.visualstudio.com/content/problem/942169/terraformtaskv1.html?childToView=942620)

The below pipeline code:
```
# Download terraform.tfvars file for keys and credentials
- task: DownloadSecureFile@1
  name: terraformvars
  displayName: 'Download Security Credentials'
  inputs:
    secureFile: 'terraform.tfvars'

- task: TerraformTaskV1@0
  displayName: 'Terraform: Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: |
      -input=false -auto-approve -var-file='$(terraformvars.secureFilePath)'
    environmentServiceNameAzureRM: '$(backendServiceArm)'
    backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
    backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
    backendAzureRmContainerName: '$(backendAzureRmContainerName)'
    backendAzureRmKey: '$(backendAzureRmKey)'
```
Always reports the error:
```
/opt/hostedtoolcache/terraform/0.12.21/x64/terraform apply -input=false -auto-approve -var-file='/home/vsts/work/_temp/terraform.tfvars'

Error: Failed to read variables file

Given variables file '/home/vsts/work/_temp/terraform.tfvars' does not exist.
```

**Comment by rrmistry** [comment]
The secure file gets downloaded to the agent's temporary folder. It persists if I copy it to the local working directory (where my git code is cloned). So I have to manually clean up after pipeline finishes.

The issue is that this command line argument `-var-file='$(terraformvars.secureFilePath)'` for terraform should work for the secure file located in temp folder but it doesn't.

I have even confirmed that the file exists using `ls --all` command before and after `'Terraform: Apply`

Terrible workaround:
```
# Download terraform.tfvars file for keys and credentials
- task: DownloadSecureFile@1
  name: terraformvars
  displayName: 'Download Security Credentials'
  inputs:
    secureFile: 'terraform.tfvars'


- task: CmdLine@2
  displayName: 'Copy terraform.tfvars to local working directory'
  inputs:
    script: |
      mv '$(Agent.TempDirectory)/terraform.tfvars' './terraform.tfvars'


- task: TerraformTaskV1@0
  displayName: 'Terraform: Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: |
      -input=false -auto-approve
    environmentServiceNameAzureRM: '$(backendServiceArm)'
    backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
    backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
    backendAzureRmContainerName: '$(backendAzureRmContainerName)'
    backendAzureRmKey: '$(backendAzureRmKey)'


- task: CmdLine@2
  displayName: 'Cleanup terraform.tfvars from local working directory'
  inputs:
    script: |
      ls --all
      rm './terraform.tfvars'
      ls --all<br>
```
Would like to fix this please because if there is an error then I need complex logic to clean up the secure file from working directory.

Additional details:
```
pool:
  vmImage: 'ubuntu-latest'
```
