### ISSUE TITLE
Pwsh does not output errors when ErrorActionPreference is set to Stop

### ISSUE THREAD

**Issue by deadlydog** [microsoft/azure-pipelines-extensions#803]
When using Pwsh and the `ErrorActionPreference` is set to `Stop`, the error text is not written the log.

As a quick and easy example, this is the yaml task I've included in the pipeline:

```yaml
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$does.not.exist()'
```

This is the output given when using Windows PowerShell:
![image](https://user-images.githubusercontent.com/1187140/78600903-0ad91f00-7811-11ea-9c00-165163778fef.png)

When enabling PowerShell Core the yaml task becomes:

```yaml
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$does.not.exist()'
    pwsh: true
```

And this is the output given when using Pwsh:
![image](https://user-images.githubusercontent.com/1187140/78600845-f2690480-7810-11ea-9c07-1c5c7e3d69fc.png)

Notice that the error details are missing from the output.

This makes it extremely difficult to troubleshoot problems, especially since `Stop` is the default `ErrorActionPreference`.

I reproduced this by creating a brand new pipeline that runs on the Azure Pipelines agents (not an on-prem agent, just to be clear). Here's the entire yaml file contents:

```yaml
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$does.not.exist()'
    pwsh: true
```

It seems that the bug only exists in Windows. If I use:

```yaml
pool:
  vmImage: 'ubuntu-latest'
```

Then the error is displayed as expected.

**Comment by SteveL-MSFT** [comment]
If you do:

```
script: '$ErrorView = "NormalView";$does.not.exist()'
```

Does the error message show?

**Comment by deadlydog** [comment]
Hey @SteveL-MSFT , thanks for responding :) 

Yes, adding `$ErrorView = "NormalView"` does indeed seem to fix the issue.

I also updated my original post to include a bit more info. It seems this bug only exists on Windows and not Ubuntu.

Hopefully that gives you enough info to track down and get the breaking change fixed 👍

**Comment by SteveL-MSFT** [comment]
@deadlydog thanks for the confirmation.  Could you do one more thing to help diagnose this? 

```
script: '$does.not.exist();get-error'
```

I'm thinking that the ConciseView formatting script has an issue in this environment.  `Get-Error` will get more information so I can inspect the code to see where it might be failing.  Note that we've already made a fix for some cases where the error message doesn't show so this might already be fixed and just waiting for a 7.0.1 release.

**Comment by deadlydog** [comment]
Sure. Here's the new yaml:

```yaml
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$does.not.exist();get-error'
    pwsh: true
```

and the output:
![image](https://user-images.githubusercontent.com/1187140/78831653-3988fe00-79a7-11ea-926c-18c6c8677a76.png)

Looks like no error details again.

Thanks @SteveL-MSFT !

**Comment by SteveL-MSFT** [comment]
@deadlydog thanks for trying that, too bad there isn't more info which is now equally perplexing.  Can you try one more thing?  Use the example in this [gist](https://gist.github.com/TylerLeonhardt/aeda3dbf5b1854736fe8e1ada2e143dc) to deploy the daily build off master branch to see if we've already fixed this in 7.1.  Thanks.

**Comment by deadlydog** [comment]
Alright, I updated the yaml to this:

```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Installing PowerShell Daily..."
      
      # Use `AGENT_TEMPDIRECTORY` to make sure the downloaded PowerShell is cleaned up.
      $powerShellPath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'powershell'
      Invoke-WebRequest -Uri https://aka.ms/install-powershell.ps1 -OutFile ./install-powershell.ps1
      
      ./install-powershell.ps1 -Destination $powerShellPath -Daily
      
      # Using `prependpath` to update the PATH just for this build.
      Write-Host "##vso[task.prependpath]$powerShellPath"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $PSVersionTable
      $does.not.exist()
    pwsh: true
```

And it looks like using the latest PowerShell 7 does indeed fix this issue 🎉
![image](https://user-images.githubusercontent.com/1187140/78841722-57605e00-79bb-11ea-92dc-d094c3b8c521.png)

Thanks @SteveL-MSFT 👍
