### ISSUE TITLE
terraform plan: Save human readable plan to file

### ISSUE THREAD

**Issue by DanielLarsenNZ** [microsoft/azure-pipelines-extensions#808]
It doesn't seem possible to write the human readable output of `terraform plan` to a file using this Task. For example, this does not work:

```
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  inputs:
   command: plan
   commandOptions: '-out=tfplan &> $(Build.StagingDirectory)/TFPlan.txt'
```

It would be super helpful if we could output the human readable plan to a file.

[This code](https://github.com/microsoft/azure-pipelines-extensions/blob/master/Extensions/Terraform/Src/Tasks/TerraformTaskV1/src/base-terraform-command-handler.ts#L189) removes a temp file that contains the human readable plan. I propose 1. a Task property that, when true, does not remove the file and 2. an output variable that contains the path to the file.

For example:

```
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  inputs:
   command: plan
   commandOptions: '-out=tfplan'
   saveHumanReadablePlan: true
```
