### ISSUE TITLE
State of Terraform is not syncing to AWS S3

### ISSUE THREAD

**Issue by LukvonStrom** [microsoft/azure-pipelines-extensions#816]
Dear Azure DevOps Development Team,
I tried to setup the Terraform Extension to deploy terraform to my AWS environment.
Unfortunately it seems like the extension is unable to sync the state with S3.

Pipeline Configuration:
```yaml
trigger:
- master
- develop

pool:
  name: test

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.3'
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infrastructure'
    backendServiceAWS: 'development-cloud'
    backendAWSBucketName: 'terraform-state-ci-sp21'
    backendAWSKey: 'terraform.tfstate'	
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infrastructure'
    environmentServiceNameAWS: 'development-cloud'	
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infrastructure'
    environmentServiceNameAWS: 'development-cloud'
```

Logs indicating that the state can't be found (from the plan command):
```
Plan: 5 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

e:\agent2\_tool\terraform\0.12.3\x64\terraform.exe version
Terraform v0.12.3
+ provider.aws v2.61.0

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from www.terraform.io/downloads.html
Too many command line arguments. Configuration path expected.
Terraform couldn't read the given file as a state or plan file.
The errors while attempting to read the file as each format are
shown below.

State read error: Error loading statefile: open e:\agent2\408\s\plan-binary-9bd9fb14-d4f8-48ec-9e6e-44cf0300999e.tfplan: The system cannot find the file specified.

Plan read error: open e:\agent2\408\s\plan-binary-9bd9fb14-d4f8-48ec-9e6e-44cf0300999e.tfplan: The system cannot find the file specified.
```

The service connection: 
![image](https://user-images.githubusercontent.com/8446619/81670886-906f7080-9448-11ea-90e6-e569f5b0a6f7.png)

Thanks in advance for your help!
