### ISSUE TITLE
TerraformTaskV1: Unable to use AzureRM backend (for tfstate file)

### ISSUE THREAD

**Issue by terminalstderr** [microsoft/azure-pipelines-extensions#820]
With a very basic pipeline that uses an Azure Storage Account for its backend (tfstate file), I see the following error. 

```
##[error]Error: Input required: environmentServiceNameAzureRM
```

![image](https://user-images.githubusercontent.com/2552438/82458595-b5c53580-9a6b-11ea-9d71-d3e4e8182c81.png)

I've captured the simplest example I could imagine in [my azdevops-terraform-plugin-tinker github repository](https://github.com/terminalstderr/azdevops-terraform-plugin-tinker). I've copied the code below in this issue for you to review. Feel free to fork the repository and import this project into your Azure DevOps & Cloud!
* https://github.com/terminalstderr/azdevops-terraform-plugin-tinker

### DevOps Pipeline YAML
* To test, replace all hardcoded values with valid values for your Azure Cloud/DevOps environment.
  * 'd88e0c85-dev-subscription'
  * 'terraform-rg'
  * 'terraform03'
  * 'tfstate'
```
# Simple example pipeline that simply aims to run terraform plan!
pool:
  vmImage: 'Ubuntu-18.04'
trigger: none

steps:
# Install Terraform
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.24'
# Run 'terraform init'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '.'
    backendServiceArm: 'd88e0c85-dev-subscription'
    backendAzureRmResourceGroupName: 'terraform-rg'
    backendAzureRmStorageAccountName: 'terraform03'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'azdevops-terraform-plugin-tinker.tfstate'
# Run 'terraform plan'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '.'
    backendServiceArm: 'd88e0c85-dev-subscription'
    backendAzureRmResourceGroupName: 'terraform-rg'
    backendAzureRmStorageAccountName: 'terraform03'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'azdevops-terraform-plugin-tinker.tfstate'
```

### Terraform file.
* To test, replace all hardcoded values with valid values for your Azure Cloud/DevOps environment.
  * "d88e0c85-6145-437a-99a3-64e8900098a7"
  * "terraform03"
  * "tfstate"
```
provider "azurerm" {
  version         = "~>2.0"
  subscription_id = "d88e0c85-6145-437a-99a3-64e8900098a7"
  features {}
}

terraform {
  backend "azurerm" {
    storage_account_name = "terraform03"
    container_name       = "tfstate"
    key                  = "azdevops-terraform-plugin-tinker.tfstate"
  }
}
```

_Originally posted by @terminalstderr in https://github.com/microsoft/azure-pipelines-extensions/issues/747#issuecomment-631505702_
