### ISSUE TITLE
Terraform Plan/Apply unable to read state file from another subscription

### ISSUE THREAD

**Issue by slawchod** [microsoft/azure-pipelines-extensions#830]
Hi,

We have created central storage account in separated subscription to store state files in secure location. In single stage we have terraform init which is using service connection A to subscription A (for backend setup) and in next step we are having terraform plan or apply with service connection B to subscription B. Addition SPN under B has rights to storage account from A.

Such setup was working for couple of months but after 25th of May (more or less) something has changed and we have started to get following errors on plan/apply.

`Error: Error loading state: Error retrieving keys for Storage Account "<storage_account_name>": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '<resource_group_name>' could not be found`

Init itself was successful all the time. There was no code change on our side. We even extended permissions for tests and we set Contributor for B SPN to entire A subscription but issue was the same.

The strange thing is that successful (prior issue) and failed steps have the same Terraform extension version: 0.0.142. We install Terraform version 0.12.3. 

We have some kind of workaround but it would require reconfiguration in many release pipelines and tens of commits. If you could revert change in extension it would be great. Thanks!

**Comment by cuzza0** [comment]
@slawchod Are you able to detail the workaround you have in place? I am having a similar issue, would be good to see what options there are.

**Comment by slawchod** [comment]
Hi @cuzza0,

No problem. So in Azure DevOps within terraform init you are specifying all terraform backend details. Previously it was sufficient for terraform plan/apply, so in code it was like that:

```
terraform {
     backend "azurerm" {}
 }
```

Now, when terraform backend settings from Azure DevOps are not taken fully from init to plan/apply I've changed code to include subscription details in backend config in the code as well:

```
terraform {
     backend "azurerm" {
       subscription_id = "#{tfbeSubscriptionId}#"
     }
 }

You might have a static value for subscirption_id, but I prefer to have it as variable and perform replace token task as the fist step in the stage.

I hope it will help :)

Cheers!
```

**Comment by NK74** [comment]
Hi

I recently faced the same issue "_Terraform: Allow state files to be stored in a different subscription_" #707

I'm trying to deploy Azure resources and states in different subscriptions too :
- 1 Central Subscription to store tfstates
- "n" subscriptions to deploy Azure resources 

I had the same 404 issue before, thanks @slawchod :1
> ```
> terraform {
>      backend "azurerm" {
>        subscription_id = "#{tfbeSubscriptionId}#"
>      }
>  }
> ```

Now I'm getting a 403 Error on my "tsfate" storage container
`Error: Error loading state: Error retrieving keys for Storage Account "XXXXXX": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxxxxxxxxxxxxxxxxxxx' with object id 'xxxxxxxxxxxxxxxxxxxx does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/ssssssssssssssssssssssssss/resourceGroups/My-Central-States-123/providers/Microsoft.Storage/storageAccounts/centralstorageblabla' or the scope is invalid. If access was recently granted, please refresh your credentials."`

Azure Pipeline YML (Terraform Extension) : Despite using the parameter "**backendServiceArm**" (The Service Connection used for my TFStates Subscription & RG) Terraform is still using the parameter "**environmentServiceNameAzureRM**" (The Azure Environnement to deploy resource. This SP should not have the privileges to the TFSates Sub/RG)

Find below my Azure Pipeline Task yml (Terraform extension)
```
    - task: TerraformTaskV1@0
      displayName: 'Terraform Plan'
      name: terraformPlan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: '#### SP used to deploy Azure Resources in my dev subscription**'
        backendServiceArm: '#### SP used to centralize Tfstates in my backend subscription'
        backendAzureRmResourceGroupName: 'My-Central-States-123'
        backendAzureRmStorageAccountName: 'mycentralstorage'
        backendAzureRmContainerName: 'mycentral-container-states'
        backendAzureRmKey: 'terraform.tfstate'
        workingDirectory: .......................
```


I tried several configurations... Do you have an idea?

Thanks
