### ISSUE TITLE
TerraformTaskV1 : Unable to set backendServiceArm with a variable coming from variable group or template import

### ISSUE THREAD

**Issue by didaskein** [microsoft/azure-pipelines-extensions#832]
All variables are working in the task below except **backendServiceArm** :

```
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
    displayName: 'Terraform : Init $(Environment)'
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
      backendServiceArm:  ${ServiceConnectionNameTerraform}   # NOT WORKING
      backendAzureRmResourceGroupName: '$(BackendStorageResourceGroupName)'
      backendAzureRmStorageAccountName: '$(BackendStorageAccountName)'
      backendAzureRmContainerName: '$(BackendStorageContainerName)'
      backendAzureRmKey: '$(Environment).terraform.tfstate'
```

Syntaxe try: 
-  **${ServiceConnectionNameTerraform}**    Not Working
![image](https://user-images.githubusercontent.com/13362276/85876231-b2913800-b7d5-11ea-8a47-d5ec13484565.png)

-  **${{variables.ServiceConnectionNameTerraform}}**    Not Working
![image](https://user-images.githubusercontent.com/13362276/85876040-6b0aac00-b7d5-11ea-89af-d2d3da31113d.png)

-  **$[variables.ServiceConnectionNameTerraform]**    Not Working
![image](https://user-images.githubusercontent.com/13362276/85876429-01d76880-b7d6-11ea-92b4-2e05f15c1150.png)

![image](https://user-images.githubusercontent.com/13362276/85876148-98575a00-b7d5-11ea-906a-6cb4a9bbb7a2.png)
[link](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)

I'm using the same variable group import for WebApp deployement and the Service connection ${ServiceConnectionName} is working perfectly. But not with TerraformTaskV1  :-( 

I have also try to create an external Yaml variable file like this : 
File : _MyProject.Development.yaml_
Content  
 ```
 variables:
    - name: ServiceConnectionNameTerraform
      value: 'My Service Connection Name in Devops'
      readonly: true

    - name: BackendStorageAccountName
      value: 'myaccountname'
      readonly: true

    - name: BackendStorageContainerName
      value: 'mycontainername'
      readonly: true

    - name: BackendStorageResourceGroupName
      value: 'myrg'
      readonly: true

    - name: Environment
      value: 'DEV'
      readonly: true
```
      
In my Release pipeline 
```
 - stage: deploy_stage_DEV
    displayName: "Deployment"
    dependsOn: build_stage
    condition: succeeded()
    variables:
      - group: MyProject.Development
      - group: MyProject.DevelopmentKV
      - template: ../variables/MyProject.Development.yaml
    jobs:
      - template: deployment-template.yml 

```

I have the **same issue with variable group & Template import**.

Thank you in advance,

**Comment by didaskein** [comment]
It's working if it's in the root level of de pipeline.
**It's NOT working when it's a variable group or template import at stage level (DEV for example)**

```
trigger:
  branches:
    include:
    - master
    - release/*
  paths:
    include:
    - deployment/pipelines/*
    - Terraform/*

pool:
  vmImage: "windows-latest"

variables:
  - group: MyProject.General
  - template: ../variables/MyProject.General.yaml  ## WORK here


stages:
  ###################################################
  # Build
  ###################################################
  - stage: build_stage
    displayName: "Build"
    jobs:
      - template: build-template.yml
      
       
  ###################################################
  # Release
  ###################################################
  # DEV
  - stage: deploy_Stage_Playground
    displayName: "Deployment of APIM Configuration"
    dependsOn: build_stage
    condition: succeeded()
    variables:
      - group: MyProject.DevelopmentKV
      - template: ../variables/MyProject.DEV.yaml  ## NOT WORK here
    jobs:
      - deployment: deploy_Job_Playground
        displayName: "Deploy MyProject DEV"
        environment: "DEV"
        strategy:
            runOnce:
                deploy:
                    steps:
                       - template: deployment-template.yml 
                         parameters:
                            ServiceConnectionName: $(ServiceConnectionNameTerraformDEV)
```

**Comment by Cavorter** [comment]
In my project this works fine if you use a different variable syntax and change the input value to `'${{ variables.ServiceConnectionNameTerraformDEV }}'`

**Comment by didaskein** [comment]
At the end it's not a bug it's a feature from Azure Devops : **Azure Devops need to check all permissions at the beginning of the run of the pipeline.**
see related issue : https://github.com/microsoft/azure-pipelines-agent/issues/1307#issuecomment-690584752
So we need to get the service name from root variable file. **it's impossible to get the service name from environment variable file** :(

**Comment by vnextcoder** [comment]
After spending around a day in trying to inject this variable coming from **Azure KeyVault** into Terraform Init task, I was thinking it was not being bound in the Pipeline because of **"all variables from KeyVault are marked secret"**, but I was incorrect based on what has been described by @didaskein 

There is a workaround to this Design though. 
You can have a parameter in your Template or the main pipeline named **environmentSelection** like so 

```
parameters:
    - name: environmentSelection
      displayName: Azure Application Environment
      type: string
      default: nonprod
      values:
        - prod
        - nonprod
```

and then use the same in the Terraform Init Task. 

```
- task: TerraformTaskV1@0
  displayName: "Main TF Init"
  inputs:
    provider: "azurerm"
    backendServiceArm: "MYConnection ${{parameters.environmentSelection}}"
    backendAzureRmResourceGroupName: $(TF_RESOURCE_GROUP)
    backendAzureRmStorageAccountName: $(TF_STORAGE_ACCOUNT)
    backendAzureRmContainerName: $(TF_CONTAINER_NAME)
    backendAzureRmKey: $(TF_STATE_KEY)
    command: "init"
    commandOptions: "-no-color -input=false -reconfigure"
    workingDirectory: $(System.DefaultWorkingDirectory)

```

May be this helps someone who hits the problem in future.
