### ISSUE TITLE
Run terraform -chdir mydir init using the extension

### ISSUE THREAD

**Issue by cloudhubzawsaz** [microsoft/azure-pipelines-extensions#892]
Hello team,

Is it possible to use task: TerraformTaskV1@0 to run the slightly different  command "terraform -chdir mydir init"

The extension gives me an error and says i can only run tf init, tf plan etc

**Comment by susumuf** [comment]
I'm not sure what diffrennt TerraformTaskV1 and TerraformCLI. but I bet it works with workingDirectory input.
```
- task: TerraformCLI@0
  displayName: 'Terraform Initialize'
  inputs:
    command: 'init'
    backendType: 'azurerm'
    ...
    workingDirectory: [path as you need]
```
so you can close this case.
