### ISSUE TITLE
ServiceNow extensions does not work when rerun stage.

### ISSUE THREAD

**Issue by HenrikSommer-eng** [microsoft/azure-pipelines-extensions#907]
When using the service now extensions from yaml.

It is not working if you rerun a stage again.

We have on an environment set an approval step that creates a change in service now.
After the deploy job is finish, we have added this yaml:
``` yaml
  steps:
  - task: UpdateServiceNowChangeRequest@2
    displayName: 'Close ServiceNow change [Successfull]'
    inputs:
      ServiceNowConnection: ${{ parameters.serviceNowConnection }}
      NewStatus: '7' 
      otherParameters: '{"u_close_notes": "succeeded" }'
``` 
It works fine the first time it run.
But if you rerun a stage it will fail.

The reason is that the extensions is using the system variable: `$(system.stageId)` to set  `x_mioms_azpipeline_stage_id` in service now.
On paper it seem to be correct.
But it seem there is a bug in Azure Pipeline when calculating the `$(system.stageId)` for approval steps it does not include what attempt it is and there for give different id for approval step and closing.

**Comment by HenrikSommer-eng** [comment]
Title should be change to:
ServiceNow extensions does not work when rerun stage

**Comment by yellowpanda** [comment]
The issue can be further explained this way:

Attempt #1:
* Create servicenow change with stageId = guid1
* Close servicenow change with stageId = guid1

Attempt #2:
* Create servicenow change with stageId = guid1
* Close servicenow change with stageId = guid2 (should have been guid1 or the previous line should have been guid2)    

![image](https://user-images.githubusercontent.com/4152321/105708372-a9577d80-5f14-11eb-9523-9390199e29d4.png)
![image](https://user-images.githubusercontent.com/4152321/105708290-85943780-5f14-11eb-9b65-9b53dc208f92.png)
![image](https://user-images.githubusercontent.com/4152321/105707953-043ca500-5f14-11eb-896e-f0bbce5b645a.png)

**Comment by HenrikSommer-eng** [comment]
Hi.
I assume it can take some time to fix this bug.
We are trying to create a work around while we wait.
We assume we can fix it with a proxy between azure pippeline and service now.
But we need to know how azure pipeline calculate the stage id, can some one help with that info?

**Comment by ammohant** [comment]
@pavanvamsi3  @tauhid621  can  we please help here.

**Comment by pavanvamsi3** [comment]
We also use attemptId while identifying the run. Let me go through this once. I'll get back to you.

**Comment by HenrikSommer-eng** [comment]
@pavanvamsi3 the yaml will be different in each of our solution we are adding service now integration to.

We assume it calculated something like this: guid($(system.stageName), $(system.stageAttempt))
But dont know if there are more parameters than just those 2 and how it is converted to guid

**Comment by pavanvamsi3** [comment]
```
"EndpointUrl": "$(endpoint.url)/api/now/table/change_request?sysparam_query=x_mioms_azpipeline_stage_id=$(system.stageId)&x_mioms_azpipeline_build_id=$(build.buildId)&x_mioms_azpipeline_stage_attempt=$(system.stageAttempt)&sysparm_fields=number,correlation_id"
```

We use the three `system.stageId`, `build.buildId`, `system.stageAttempt` inbuild variables to identify.

**Comment by HenrikSommer-eng** [comment]
I know you are using the same variable for creating and closing, but the problem is that system.stageId does not give the same id for creating as it does for closing.
See yellowpanda comment.

**Comment by pavanvamsi3** [comment]
Yep, gotcha. I'm trying to reproduce this. This issue will be updated.

**Comment by HenrikSommer-eng** [comment]
Any idea when we can expect a fix for this?

**Comment by pavanvamsi3** [comment]
Hey, @HenrikSommer-eng we're planning to pick this up next sprint (ETA End of March). I'll keep you updated.

**Comment by HenrikSommer-eng** [comment]
@pavanvamsi3 what is this status on this?

**Comment by pavanvamsi3** [comment]
Hello @HenrikSommer-eng Apologies, we couldn't pick it up last quarter, this needs a bigger fix than I expected.

I'll update you with the new ETA very soon.

**Comment by HenrikSommer-eng** [comment]
Hi @pavanvamsi3 

> I'll update you with the new ETA very soon.

It has now been 2 months with out any update?

**Comment by pavanvamsi3** [comment]
Hey @HenrikSommer-eng Apologies, this was a little tricky and we couldn't pick it up right away then. 

We are on leave this whole week, I'll pick this up and check after that.

**Comment by pavanvamsi3** [comment]
This has been triaged.

**Comment by HenrikSommer-eng** [comment]
@pavanvamsi3 any update?
I seem there was a release of service now extension: https://docs.microsoft.com/da-dk/azure/devops/release-notes/2021/sprint-190-update#support-for-quebec-version-of-servicenow 
But I dont know if it is related.

**Comment by pavanvamsi3** [comment]
Hey @HenrikSommer-eng that release was specific to Quebec support.

Let me follow up with the team that's owning this right now, @naga-bandi, @v-pavithrasa - Can you please check this again?

**Comment by youngm** [comment]
This is impacting me too.

**Comment by HenrikSommer-eng** [comment]
Any update @pavanvamsi3 ?

**Comment by pavanvamsi3** [comment]
@Naga-bandi - Any update on this, this was being looked into right?

**Comment by HenrikSommer-eng** [comment]
@pavanvamsi3 any one else than NAGA-BANDI who can help with an updated?

**Comment by NAGA-BANDI** [comment]
@HenrikSommer-eng, @pavanvamsi3: My apologies on this delay.
@v-abajaj: Can you please look into this?

**Comment by HenrikSommer-eng** [comment]
@NAGA-BANDI v-abajaj dont seem to response.

**Comment by HenrikSommer-eng** [comment]
@v-abajaj.

It sound like your setup is correct.
Our check look like this:
![image](https://user-images.githubusercontent.com/60382556/136928480-cb546262-9133-4ac6-bba6-f63c615daca1.png)

And it is working the first time we run it.
Our yml is almos the same:
```
  - task: UpdateServiceNowChangeRequest@2
    displayName: 'Close ServiceNow change [Successfull]'
    inputs:
      ServiceNowConnection: 'ServicenowConnection'
      NewStatus: '7' 
      otherParameters: '{"u_close_notes": "succeeded" }'
```
If it is not working you will have to look into the log of task: UpdateServiceNowChangeRequest
It shuold be calling: 
`[servicenow url]api/now/table/change_request?sysparm_query=x_mioms_azpipeline_stage_id=[stage id]^x_mioms_azpipeline_build_id=[build id]^x_mioms_azpipeline_stage_attempt=[attempt]&sysparm_fields=number,correlation_id`

**Comment by HenrikSommer-eng** [comment]
@v-abajaj ChangeRequestNumber is not mandatory. I can see the UI is indicate it is.
The yaml I provoided is working.

When you run the pipeline you should see that start by calling the URL:
`[servicenow url]api/now/table/change_request?sysparm_query=x_mioms_azpipeline_stage_id=[stage id]^x_mioms_azpipeline_build_id=[build id]^x_mioms_azpipeline_stage_attempt=[attempt]&sysparm_fields=number,correlation_id`
After that it get correlation_Id and change request number.

You can see our logs from yellowpanda post: https://github.com/microsoft/azure-pipelines-extensions/issues/907#issuecomment-766796353

**Comment by HenrikSommer-eng** [comment]
@v-abajaj how is it going with this?
Do you have any estimate on when we can expect a fix for this?

**Comment by HenrikSommer-eng** [comment]
@v-abajaj, @pavanvamsi3 @NAGA-BANDI 
We been waiting 10 months.
The product does not work and you can't tell when you expect this to be fixed?

**Comment by pavanvamsi3** [comment]
@NAGA-BANDI can you please prioritize this? I remember having a discussion with Akshay and giving him some pointers.

**Comment by v-hinti** [comment]
Attempt # 1:

Create servicenow change with stageId = guid1
Close servicenow change with stageId = guid1
Attempt # 2:

Create servicenow change with stageId = guid1
Close servicenow change with stageId = guid2 (should have been guid1 or the previous line should have been guid2)

 as i checked above mentioned thing is happening. but i want to know system variables is updating in task  if we  re run ?  back end is updating new stage id if we run stage but I'm not sure same is updating in system variables?

$(endpoint.url)/api/now/table/change_request?sysparm_query=**x_mioms_azpipeline_stage_id=$(system.stageId)**^x_mioms_azpipeline_build_id=$(build.buildId)^x_mioms_azpipeline_stage_attempt=$(system.stageAttempt)&sysparm_fields=number,correlation_id",

=**$(system.stageId)** need to update for every new stage id while Create ServiceNow change ? can any one help on this to verify task  as i verified  we are sending new stage id to task

**Comment by HenrikSommer-eng** [comment]
@v-hinti I'm not sure if you ask me to verify something or it is maybe @pavanvamsi3 ?

For me it would be more logic if stageId remained the same for each re run, and if it did the service now extensions would work.

**Comment by bbarman4u** [comment]
_The way the logic of this extension is implemented makes it very tightly coupled to the job and environment definition and makes it susceptible to failures since it does not take into account re-runs or or how we may have impacts to the downstream processes. Since change request id is kind of the primary key, identification of that in a robust way (as explained in this year long post) and then having that set as some form of pipeline level variable would make the extension truly reusable & useful especially for multi stage yaml pipelines._

Example scenarios I am also running into, due to failures of any tasks in the stage where the environment check and change management tasks are configured today below -

But I am not able to capture the value of the change request for using it in a downstream job or task. Specifically, I wan’t to segregate the Release Gate Stage separately from the actual production deployment stage since otherwise if I re run any failed deployment stage or failed smoke tests, it ends up creating a new Change Request.

*   Currently, stage are like this : `dev -> test -> prod`  
    where **prod** includes creating change request based on env check, tasks to deploy if change request is ready to implement), update the change request after deployment and close out
    
*   Desired : `dev -> test -> pre-deploy-gate -> prod -> smoke-test -> close-change-req`  
    where **pre-deploy-gate** includes creating change request based on env check  
    where **prod** includes jobs to deploy if change request is ready to implement and the previous stage was passed  
    where **close-change-req** includes jobs to update the change request after deployment and smoke tests have passed.

@pavanvamsi3 @v-abajaj @NAGA-BANDI Can we achieve the above desired state, if we have the ability to make the change request # and any other related system variable persist-able across different stages OOB ?

**Comment by HenrikSommer-eng** [comment]
@pavanvamsi3 I see you have created a pull request, do you have any estimate on when it will be released?

**Comment by HenrikSommer-eng** [comment]
@pavanvamsi3 why is this not merge yet?

**Comment by HenrikSommer-eng** [comment]
Sorry for tagging you all, but can any of you give an update?

@pavanvamsi3 @NAGA-BANDI @v-hinti @v-abajaj @ammohant

**Comment by HenrikSommer-eng** [comment]
Sorry for tagging you all, but can any of you give an update?

@pavanvamsi3 @NAGA-BANDI @v-hinti @v-abajaj @ammohant

**Comment by pavanvamsi3** [comment]
@HenrikSommer-eng Apologies, but I've left the team and don't have an update on it.

@NAGA-BANDI what's the status on this sir? It's been super long, please keep the thread updated if there's any blocker.

**Comment by v-hinti** [comment]
hi @HenrikSommer-eng we have fixed the re-run stage issue in local private accounts, but we have facing issue with test environment. so finally, we have fixed the issue and changes ready to move to production mean while the customer who are getting issue Thay can do one round of (uat) in our accounts (will give access to our accounts) if everything fine we will move to production 
![image](https://user-images.githubusercontent.com/92420394/165887657-c80b0f04-645c-42e5-9939-f2f06f209b04.png)
![image](https://user-images.githubusercontent.com/92420394/165887741-c5b3bfdd-e63b-4076-9671-18b5841e40c5.png)

**Comment by HenrikSommer-eng** [comment]
@v-hinti That sound greate.
I can help with the UAT if you want me to.

**Comment by v-hinti** [comment]
can we schedule the meeting?

**Comment by v-hinti** [comment]
please mention your availability will schedule the meeting

**Comment by v-hinti** [comment]
hi @HenrikSommer-eng please mention your free time will schedule the meeting

my team's id v-hinti@microsoft.com

**Comment by HenrikSommer-eng** [comment]
I have time the next 2 hours today.
Tomorrow and Wednesday I have time from 6am to 4 pm UTC time.
Friday from 7am to 1pm UTC time.

**Comment by v-hinti** [comment]
scheduling 4:30 pm as per ist i think it's suitable

**Comment by v-hinti** [comment]
your id please!

**Comment by HenrikSommer-eng** [comment]
You get not get my mail  i send to v-hinti@microsoft.com?

**Comment by v-hinti** [comment]
notifications@github.com this one? otherwise you can send to [v-hinti@microsoft.com]

**Comment by HenrikSommer-eng** [comment]
I did send to v-hinti@microsoft.com.

By email is hsm@energinet.dk

**Comment by HenrikSommer-eng** [comment]
The solutions is fixing our problem, I approve it.

**Comment by HenrikSommer-eng** [comment]
When can we expect this change to be rolled out?

**Comment by HenrikSommer-eng** [comment]
When will this be released?

**Comment by HenrikSommer-eng** [comment]
@pavanvamsi3 @NAGA-BANDI @v-hinti @v-abajaj @ammohant does any of you have any info on when this will be rolled out?

**Comment by pavanvamsi3** [comment]
I think @rvairavelu's team is handling it right now, let me PM them as well.

**Comment by v-snalawade** [comment]
Hi @HenrikSommer-eng 
We have updated the changes and we could see that stages are rerunning successfully.

![image](https://user-images.githubusercontent.com/98255332/177928557-ce001281-89be-49cc-afd9-53ef57dda922.png)

Can you please check and confirm on this.

**Comment by HenrikSommer-eng** [comment]
Hi @v-snalawade 

I have now checked it and can not confirm it.
I dont think your change is rolled out yet.

1. the extenstions was last updated in 2021:
![image](https://user-images.githubusercontent.com/60382556/178938611-aecdd45a-8a21-46f4-8d7a-81583badb484.png)

Also the API version seem wrong if i compare with the PR.
The API that create the change is: (Gate)
Task         : ServiceNow Change Management
Description  : Gate on status of new change request or an existing change request in ServiceNow.
Version      : 2.176.0
Author       : Microsoft

The task that need to update the change is:
Task         : Close ServiceNow change [Successfull]
Description  : Update ServiceNow change request
Version      : 2.183.0
Author       : Microsoft

**Comment by v-snalawade** [comment]
Hi @HenrikSommer-eng ,
We could see that changes are deployed to production. I tried at my account and it is rerunning successfully with existing extension. As we have not updated the extension it is showing the version as 4.186.1 

We have updated the files for task issue 
![image](https://user-images.githubusercontent.com/98255332/180936177-2daec973-d3ee-433d-ae38-8fa002e080a1.png)

If you are still facing issue to rerun the stage please let me know.

**Comment by HenrikSommer-eng** [comment]
Hi @v-snalawade 

We are still facing the issue.
The issue is still it is using stage Id from attempt 1.
let me share the yml file:
```yml
trigger:
  branches:
    include:
    - none
stages:
- stage: ServiceNowDev
  displayName: 'Deploy to Dev'
  jobs:
  - job: deploy_Infrastructure
    displayName: Dummy deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: inline
        displayName: Test Task
        script: echo "Hello from deploy"
  - job: 'serviceNowCloseChangeSucceeded'
    displayName: 'Close service now change [Successfull]'
    dependsOn:
    - deploy_Infrastructure
    condition: succeeded()
    pool:
      name: Server
    steps:
    - task: UpdateServiceNowChangeRequest@2
      displayName: 'Close ServiceNow change [Successfull]'
      inputs:
        ServiceNowConnection: ServiceNow Change - TEST
        NewStatus: '7'
        otherParameters: '{"u_close_notes": "succeeded" }'
  - job: 'serviceNowCloseChangeFailed'
    displayName: 'Close service now change [Failed]'
    dependsOn:
    - deploy_Infrastructure
    condition: failed()
    pool:
      name: Server
    steps:
    - task: UpdateServiceNowChangeRequest@2
      displayName: 'Close ServiceNow change [Failed]'
      inputs:
        ServiceNowConnection: ServiceNow Change - TEST
        NewStatus: '11'
        otherParameters: '{"u_close_notes": "failed"}'
  - job: 'serviceNowCloseChangeCanceled'
    displayName: 'Close service now change [Canceled]'
    dependsOn:
    - deploy_Infrastructure
    condition: canceled()
    pool:
      name: Server
    steps:
    - task: UpdateServiceNowChangeRequest@2
      displayName: 'Close ServiceNow change [Canceled]'
      inputs:
        ServiceNowConnection: ServiceNow Change - TEST
        NewStatus: '9'
        otherParameters: '{"u_close_notes": "Canceled"}'
- stage: DummyStage
  displayName: 'Deploy to Dev # so I can retry'
  jobs:
  - job: deploy_Infrastructure
    displayName: 'Dummy deploy'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        displayName: 'Test Task'
        script: |-
          echo "Hello from deploy"

```
