### ISSUE TITLE
TerraformTaskV1: how to store state on GCP bucket via service connection?

### ISSUE THREAD

**Issue by hazcod** [microsoft/azure-pipelines-extensions#934]
Hi, where can I find the documentation on how to use the TerraformTaskV1 to store state in a GCP S3 bucket?
I can only find some general documentation that references AzureRM only.

e.g.
```yaml
stages:
  - stage: Terraform_Validate_Plan
    displayName: Validate & Plan Terraform code
    condition: eq(variables['Build.Reason'], 'PullRequest')
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: terraform_validate_plan
        steps:
          - checkout: self
            clean: true
          - task: TerraformTaskV1@0
            displayName: install terraform
            inputs:
              terraformVersion: latest
          - task: TerraformTaskV1@0
            displayName: "terraform init"
            inputs:
              command: "init"
              workingDirectory: terraform/
          - task: TerraformTaskV1@0
            displayName: "terraform validate"
            inputs:
              command: "validate"
              workingDirectory: terraform/
          - task: TerraformTaskV1@0
            displayName: "terraform plan"
            inputs:
              command: plan
              workingDirectory: terraform/
              provider: gcp
              backendServiceArm: AzureRM
              backendServiceGCP: "my-service-connection"
              backendGCPBucketName: "terraform-gcloud-state"
              args: -var=project_id="myprojectid"
```

```
Job terraform_validate_plan: Step TerraformTaskV14 input backendServiceArm references service connection AzureRM which could not be found
```
